### ISSUE TITLE
Add customizeable info section

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-status#17]
For instances where there is maintenance that might not be accurately reflected in other sections, for example knowing the database will go up and down. This could be as simple as a section in the index.html that's easy to comment out when not needed.

**Comment by olafveerman** [comment]
Wouldn't it be better to have this on the status endpoint? Before a change in `index.html` goes through the build process...

Also:

1. do you want to schedule maintenance? That would allow us to include a warning in advance
2. is the db the only component where you foresee maintenance?

**Comment by jflasher** [comment]
I think something editable not tied to the API would be good in case the API itself is down. I'm thinking just a general comment box at the top. Don't think it'll be necessary all that much, just would've been nice over the weekend. 

I'm all for scheduling maintenance, but the full-time devops staff are really unreliable. 😁
