### ISSUE TITLE
Most endpoints return errors, yet API is reported OK

### ISSUE THREAD

**Issue by dolugen** [openaq/openaq-status#18]
I'm seeing 500 and 503s on most endpoints (all except countries), but status.openaq.org reports green.

**Comment by jflasher** [comment]
May be intermittent issues with ELB routine causing some requests to fail (and then be cached). Will check it out tomorrow.

**Comment by jflasher** [comment]
This is interesting, looks like one of the instances went wonky (fetch task was stuck running and api wasn't staying up). New Relic shows an increase in the error rate but doesn't change the status. I'll dig around New Relic and see if I can change that.
