### ISSUE TITLE
500 error on measurements v2, v1 and averages v1 with default parameters

### ISSUE THREAD

**Issue by bcorbett6** [openaq/openaq-status#27]
Hi there,

Is there currently a system outage? I haven't been able to get any data back from the v1 or v2 API for days (500 error response).

**Comment by russbiggs** [comment]
thanks for reporting.  The canary test we have on measurements is showing some slower response times but not getting 500s. Can you share the queries you're getting the 500 error on? I can try to add them into our canary testing for the status.

**Comment by bcorbett6** [comment]
Hi @russbiggs , appreciate the speedy response. Specifically getting the 500 response on measurements v2.

curl -X 'GET' \
  'https://u50g7n0cbj.execute-api.us-east-1.amazonaws.com/v2/measurements?date_from=2000-01-01T00%3A00%3A00%2B00%3A00&date_to=2022-03-25T16%3A50%3A00%2B00%3A00&limit=5&page=1&offset=0&sort=desc&radius=1000&order_by=datetime' \
  -H 'accept: application/json'

Looks like I've been getting it since 14.00 UTC on 16/03/2022

**Comment by russbiggs** [comment]
@bcorbett6 We've gotten the system back up and running, the URL you've shared is working. I've added a new check in our status canaries to better cover issues in the measurements endpoint.
