### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by olafveerman** [openaq/openaq-status#3]
@jflasher Where do you propose the status page to be hosted? gh-pages or S3? If the latter, could you create a bucket?

Not time-sensitive

**Comment by jflasher** [comment]
Let's keep it on S3 to match others. Once there is something deployable in repo, I'll create bucket, redirects and such.

**Comment by olafveerman** [comment]
`develop` is deployable and ready from our point of view. Let me know if there's anything I can do to set this up.

@jflasher

**Comment by jflasher** [comment]
Looking at this now.

**Comment by jflasher** [comment]
I can't successfully run `npm run build`, it's complained about missing `clean` and `images` tasks.

**Comment by olafveerman** [comment]
All of this is fixed.
