### ISSUE TITLE
Design review

### ISSUE THREAD

**Issue by olafveerman** [openaq/openaq-status#5]
@ascalamogna The status page is ready for your review.

I tried to keep as simple as possible and used the `openaq-design-system` to apply some styling.

![image](https://cloud.githubusercontent.com/assets/751330/19854402/2ae7e73e-9f45-11e6-85d4-94f396e0ce3b.png)

This is how warnings on the Fetch section are shown and stacked:

![image](https://cloud.githubusercontent.com/assets/751330/19854466/7a161876-9f45-11e6-9eed-340ff6c5180d.png)

Let me know if you need anything. To run status locally, you'll also need to run the API locally.

cc @danielfdsilva

**Comment by jflasher** [comment]
😻 love seeing this info get presented somewhere!

**Comment by olafveerman** [comment]
Closed through https://github.com/openaq/openaq-status/pull/7
