### ISSUE TITLE
Review statuses

### ISSUE THREAD

**Issue by olafveerman** [openaq/openaq-status#6]
The functionality of the status page is implemented. We're still revising the style and layout, but it's ready for your review.
Most importantly, please review the statuses and feedback messages.

## API health
Here we are fetching the status from New Relic. Their `green`, `orange`, `red` system is a bit ambiguous, so it's hard to come up with a very descriptive error message. For now we have:

| New Relic | Our status message |
| --- | --- |
| green | API is up and running |
| orange | Something's not right |
| red | The API is down |
| unknown | API health unknown |

### API Fetch
On the API Fetch side, we are doing a couple of checks.

| Reason | Type | Message |
| --- | --- | --- |
| Can't fetch the results | info | The API is down, can\'t determine the status of OpenAQ fetch |
| Last fetch too old | warning |  The last fetch started more than 12 minutes ago. |
| No recent results | warning | The last five fetches yielded no results |
| No info or warning | success | Fetch seems to be working properly |

At the moment, there is nothing that really causes an error message on fetch.

@jflasher @RocketD0g Some feedback on this would be great. Anything else that we can determine from either the New Relic API or the fetches endpoint?

**Comment by jflasher** [comment]
@olafveerman this looks like a great start to me. For the New Relic bits, I think the color is mostly related to an index they make based on response time. It's not really a up/down thing but rather a fast/slow thing. I might rephrase messages to be like or similar

| New Relic | Our status message |
| --- | --- |
| green | API is up and running |
| orange | We're seeing some slow down in response times |
| red | We're seeing significant slow down in response times |
| unknown | API health unknown |

I think there are a ton of things we can dig into with the fetch results, but not sure we need to go too deep on this initial piece. I think if any of the fetches show 0 inserts (not just all of last 5), that'd probably indicate a problem. Some of the more advanced things (like look at fetches for individual source over whole day) would probably require a more advanced /fetches endpoint.

**Comment by olafveerman** [comment]
Addressed in this PR https://github.com/openaq/openaq-status/pull/8
